### ISSUE TITLE
Df\Payment\ConfigProvider' not found

### ISSUE THREAD

**Issue by Kuntal32** [mage2pro/klarna#1]
Hello,
     I'm implementing klarna checkout into my osCommerse website in magento 2.1.6 and I'm getting this error during view cart. 
Fatal error: Class 'Df\Payment\ConfigProvider' not found in C:\xampp\htdocs\new_meg_test28\app\code\Dfe\Klarna\ConfigProvider.php on line 5
Please advice.
Thank you.

**Comment by dmitry-fedyuk** [comment]
Try to not ignore the official installation instructions: it would be a good skill for you during all your life.
